In [1]:
import torch
import numpy as np

# Torch tensors

## Initializing a Tensor
It can receive datas from 4 perspective:
1. Direclt from data
2. From Numpy array
3. From another tensor
4. from random or constant values

In [2]:
# Tensors can be created directly from data. The data type is automatically inferred.
data = [[1, 2, 3],[4, 5, 6]] # [2,3]
x_data = torch.tensor(data)
print(f"x_data: {x_data}", "\n", x_data.shape,"\n", x_data.dtype)

x_data: tensor([[1, 2, 3],
        [4, 5, 6]]) 
 torch.Size([2, 3]) 
 torch.int64


In [3]:
# From a Numpy array
np_array = np.array(data)
x_np = torch.tensor(np_array) # torch.from_numpy() formal function
print(f"x_np: {x_np}", "\n", x_np.shape,"\n", x_np.dtype)

x_np: tensor([[1, 2, 3],
        [4, 5, 6]]) 
 torch.Size([2, 3]) 
 torch.int64


In [4]:
# From another tensor
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
x_zeros = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zeros} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")
# If you want a tensor of zeros with shape (3,4), use torch.zeros instead:
x_zeros_new = torch.zeros((3, 4), dtype=torch.float)
print(f"Zeros Tensor with shape (3,4): \n {x_zeros_new} \n")

Ones Tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

Zeros Tensor: 
 tensor([[0, 0, 0],
        [0, 0, 0]]) 

Random Tensor: 
 tensor([[0.5610, 0.2298, 0.2094],
        [0.4241, 0.1913, 0.8751]]) 

Zeros Tensor with shape (3,4): 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



In [5]:
# From random or constant values:
rand_tensor = torch.rand((2,3))
ones_tensor = torch.ones((2,3))
zeros_tensor = torch.zeros((2,3))

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6324, 0.6010, 0.8182],
        [0.3405, 0.7864, 0.3180]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

In [8]:
tensor = torch.rand(3,4)
print (f"Random tensor: {tensor}")
print (f"Shape: {tensor.shape}")
print(f"Type: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Random tensor: tensor([[0.5980, 0.0513, 0.5007, 0.6503],
        [0.5408, 0.1214, 0.9344, 0.9638],
        [0.2120, 0.2860, 0.7308, 0.5692]])
Shape: torch.Size([3, 4])
Type: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

In [14]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(tensor.device)

mps:0


In [21]:
# Standard numpy-like indexing and slicing:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0,:]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
# Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension
tensor_cat = torch.cat([tensor, tensor, tensor],dim=1) # dim decides dimension to be concatenated, 0-> row, 1-> column
print(tensor_cat,tensor_cat.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]]) torch.Size([4, 12])


	•	@ and matmul() → Matrix multiply
	•	* and mul() → Element-wise multiply

In [27]:
# Arithmetic operations
# All of these give the same result:
y1 = tensor @ tensor.T           # Operator version
y2 = tensor.matmul(tensor.T)     # Function version

y3 = torch.rand_like(y1)         # Pre-allocate output tensor
torch.matmul(tensor, tensor.T, out=y3)  # In-place version (saves memory)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [29]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [38]:
# Single-element tensors
# If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

Note:\
In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [39]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
